# Generated by Django 5.2.7 on 2025-10-26 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_user_managers_remove_user_username'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'booked')), fields=('doctor', 'date', 'time_slot'), name='unique_active_appointment'),
        ),
    ]
