server {
    listen 80;

    server_name _;

    root /usr/share/nginx/html;
    index index.html;


    # Limit upload size to 5 MB
    client_max_body_size 5M;

    # Reverse proxy API calls to Django backend
    location /api/ {
        proxy_pass http://backend:8000/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Fallback to index.html for SPA routes
    location / {
        try_files $uri /index.html;
    }
}
