version: "3.8"

services:
  backend:
    build:
      context: ./backend_django
    container_name: app_backend
    env_file:
      - ./backend_django/.env
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend/
    container_name: app_frontend
    depends_on:
      - backend
    ports:
      - "5173:80"
    restart: unless-stopped
